// src/constants/auth.ts

export const SYSTEM_PERMISSIONS = {
  ADMIN_FULL_ACCESS: 'ADMIN_FULL_ACCESS',
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT: 'USER_EDIT',
  USER_DELETE: 'USER_DELETE',
  TENANT_VIEW: 'TENANT_VIEW',
  TENANT_EDIT: 'TENANT_EDIT',
  ORG_VIEW: 'ORG_VIEW',
  ORG_CREATE: 'ORG_CREATE',
  ORG_EDIT: 'ORG_EDIT',
  ROLE_VIEW: 'ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_EDIT: 'ROLE_EDIT',
  REQUEST_VIEW: 'REQUEST_VIEW',
  REQUEST_CREATE: 'REQUEST_CREATE',
  AUDIT_VIEW: 'AUDIT_VIEW',
} as const;

export const WILDCARD_PERMISSION = '*';
